### ISSUE TITLE
Deter use of this kind of anchors instead of id-based anchors

### ISSUE THREAD

**Issue by KOLANICH** [bokand/ScrollToTextFragment#11]
It is proposed to make this kind of links unworkable for the content within the same page.

Rationale: code-monkeys would abuse it for referencing content in own applications instead of `id`s. It can cause performance, efficiency and resource consumption problems. But code-monkeys don't care. Unfortunately sometimes even large web resources hire code-monkeys. So the standard should be foolproof.

**Comment by isiahmeadows** [comment]
You can't select these anyways unless you do a seriously complicated, slightly arcane CSS selector (which is itself a bit inaccessible to code monkeys), and with my proposal, it takes away even that. And for text search, it's not that substantially slower, not enough that abuse like this really generates a substantial *performance* problem outside larger pages that are already relatively slow to load in the first place.

**Comment by bokand** [comment]
I'm not sure I understand the issue here. Is the proposal to disallow scroll-to-text fragments on a navigation within the same document (e.g. window.hash = '...'), the existing proposal already does so in the Security section, the _Limit feature to full (non-same-page) navigations_ bit of the [Security section](https://github.com/bokand/ScrollToTextFragment/#security)

**Comment by bokand** [comment]
I'm also curious what the performance and resource consumption problems would be. Doing a text search over a file does a little more work but is trivial in comparison to loading and processing the full resource so I don't think that's a concern.

**Comment by KOLANICH** [comment]
>Is the proposal to disallow scroll-to-text fragments on a navigation within the same document (e.g. window.hash = '...'), the existing proposal already does so in the Security section, the Limit feature to full (non-same-page) navigations bit of the Security section

Indeed; thanks.

>I'm also curious what the performance and resource consumption problems would be. Doing a text search over a file does a little more work

The problem is that locating content by `textContent` is more expensive than locating an element by id. So the losses are `(cost of STTF - cost of scrolling to element located by id) * count of abuses`, where an `abuse` is using STTF istead of scrolling to `id` or `name` where there is almost no difference. If we want to minimize the losses, we either want to minimize the delta or minimize the `count of abuses`.

>but is trivial in comparison to loading and processing the full resource so I don't think that's a concern.

in order to scroll browser has to parse the source and determine bounding boxes of pieces of content anyway, doesn't it?

**Comment by isiahmeadows** [comment]
@KOLANICH 

> in order to scroll browser has to parse the source and determine bounding boxes of pieces of content anyway, doesn't it?

Try searching for `mathtt` in [this page full of LaTeX](https://katex.org/docs/supported.html). In Chrome, I get two results: one is visible and the other is not. The browser doesn't try to account for bounding boxes during page search, only display and visibility. If you want to compare all three means of hiding content, [check this out](https://p.flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8ABwB8AVUgACeFghThDAObzIDAE6wsM7lKjduAayklu6qRAZap3EjLmQMggPRiAOnQ+D4DAEYxRDykpbzkGJEC6YODvdUjo6NDRAGEAZVSXWXiEkKzUy01tRAAPeEysbISkgCUIOiQIdWRyypDneDigttlLCK7vX24kAE9W2NaY+AiAOV0weGHKTL6onO8IgHk6CGWJ3IjBMEU6US2d5yOGE92umPbO1cmHnP3RQR4G0SQyI6gGYdQUjovHOHwgb3aKxe61EABUAO7cG6PRJTN6XKLzRYQAC8bhA31+-0BwO2+LhiJcGIhaNu3WeqIZVTR7yG4IAbj8yL4KGQFoCsGQkA06C4wTSoWs0bCsE1zrSUZMDhipFiYHiQJywNzefypILhXVyTK5VTjhKxvcxh09jDWZ9uIpYHyAVIAAxitkWulK0QAMW4AFd1MjoSyVWrcfjHVYXYC3eSA8GzVdvSjMgzMoMRpFMn4ApxIDAEGReFR0AAWVAADhAAF9CPQmCx0BhYGAqMQeHw6vBWD5-PJgF1BuoGuoALQ8KB-YSQQHT2eQADcHjrHg8skIMiQUmHq0UwrIdCU8YwACYAKwQXDujDX3Cr1aj8eAgCMwmKqu4UCFUn8ViGE+daFtAcDwKWdDliAADMqBuvWAC6dZAA). When I try that in Chrome, I get this:

| CSS | Searchable |
|:-:|:-:|
| No styles | Yes |
| `display: none` | No |
| `visibility: hidden` | No |
| `opacity: 0` | Yes |

So it needs a quick CSS pass, but it does *not* need to calculate layout. In fact, it only needs to calculate two CSS properties, neither of which are inherited.

-----

Also, it's worth noting in this case, your cursor will turn into a text select cursor over the `opacity: 0` and unstyled spans, but it remains a general purpose pointer over the `display: none` and `visibility: hidden` spans.

**Comment by bokand** [comment]
The browser only has to walk the laid-out DOM tree. Depending on the implementation, it may have to do that anyway for an id match.

I just mean that by the time the page has been downloaded, parsed, run style, layout, paint, etc. the cost of doing a text search is negligible in comparison. The amount of work the browser is doing to load any given page is quite staggering.
