### ISSUE TITLE
Don't break the hash

### ISSUE THREAD

**Issue by Maxim-Mazurok** [bokand/ScrollToTextFragment#13]
Disclaimer: it's WIP issue, I will update it later, it's not finished, just sketching some ideas.

Hash is already defined and we don't want to break it. As mentioned in the readme, there might be a collision with ids and routes in SPAs. So, while I like the goal, I don't really like breaking compatibility.

Potential solutions:
1. HTML attribute. We already have HTML attributes for `<a href="...">` to tell the browser how to open the page. For example, we have `target=_blank`, `rel=noopener` and others. So, let's create a new attribute, let it be `target-text="..."`. So, one would use it like this:
`<a href="https://example.com" target-text="text to highlight">Link</a>`
It will allow us to send links wherever we can use HTML: in emails, chats, or in search engine results.
But this solution will not allow to open URLs with highlights from other programs, outside of the browser, I think.
2. Another URI scheme. We have a lot of URI schemes. Probably, most known is `mailto:` and Chrome is able to handle it perfectly, to open gmail whenever I click on it. So, why don't we create a new URI sceme, which will be something like this (similar to [Magnet URI](https://en.wikipedia.org/wiki/Magnet_URI_scheme)):
`targetTextOnPage:?targetText=text to highlight&url=https://example.com`
Which will open `https://example.com` and highlight `text to highlight`. Spaces probably should be URL-encoded, doesn't really matter right now.
But this solution don't have a fallback. So, if user with old system clicks on that "magnet" link, it won't open nothing.

Side notes:
- `[` and `]` are reserved gen-delims ([src](https://tools.ietf.org/html/rfc3986#section-2.7)) and still are not used, I think. So, probably we can do `https://example.com/page#header[text to highlight]`
- css selectors are not stable, especially because of complicated building proccess of modern web apps that use minification and obfuscation to prevent parsing, so it's not a good option.

P.S. While it's still WIP, let me know what you think about it.

**Comment by bokand** [comment]
> 1. HTML attribute

This is clean but unfortunately misses many important use cases. Two that I can think of clearly are copy/paste sharing and links from outside of DOM (e.g. Android intent). I consider these central use cases.

> 2. Another URI scheme.

I think this would work but it has the downside of being unfamiliar and a totally new thing to spec.

In general, I think the fragment is actually [defined](https://tools.ietf.org/html/rfc3986#section-3.5) for exactly this use case. I'm quite conscious of breaking existing content, but at the same time, I don't think we should compromise the design based on theoretical concerns. There's already [existing precedent](https://github.com/bokand/ScrollToTextFragment#encoding-the-text-snippet-in-the-url-fragment) for using the fragment to do very similar things.

If there's data showing that there's really no good way to modify the fragment while maintaining web-compat then I can be convinced we should explore other avenues. Absent that though, I think we should try to extend fragments. From other issues, it seems most SPA and routers use fragments of the form '#!' (indeed [this w3c text](https://www.w3.org/TR/fragid-best-practices/#consistent-script-processing) specifies '#!' is reserved for being interpreted by script). I suppose the action item here is to determine how many of those would break if we append '&targetText' or something else to the hash.

**Comment by Maxim-Mazurok** [comment]
> copy/paste sharing and links from outside of DOM (e.g. Android intent). I consider these central use cases
 
Why do you consider them central use cases? I thought that one of the biggest problems is with the google search when it shows you a relevant page, but it has also a lot of irrelevant information, so the user quits this page. In this case, highlighting text on the page will help Google to decrease the bounce rate from search results.
So, by implementing that simple and clean solution, we will cover the HTML world, it's quite a big deal.

> fragment is actually [defined](https://tools.ietf.org/html/rfc3986#section-3.5) for exactly this use case

Well, while it's defined for that usecase, it's unclear about the scheme for that usecase. Only usecase that I'm aware of, is for scrolling to headers and elements with id's. It's quite easy to handle this edge case, if we have element with `id="targetText=..."`, then browser is aware of this element and can suppress text highlighting mode and simple scroll to this element as it normally would. The roblem is that a lot of SPAs are relying on hash. And it can't be handled as easy as with id's, because browser is not really aware of internal JS app routing. It's a bad situation. And probably it's bad because RFC sais nothing about hash scheme and kinda left a lot of freedom for JS hackers, so they made SPAs the way they wanted. If there was a scheme for a hash, like `#action=scrollTo&by=id&id=MyHeader` then we could easily extend that scheme. Unfortunately, we can't. And as far as I understand, we can't just break backward compatibility in HTML 6. And I'm not sure how would we define HTML 6, since HTML 5 is just `<html>` now... so... Let's create the new web, seriously. You can't even use variables in your website styles. It's broken in so many ways and on so many levels... Sorry :)

> downside of being unfamiliar and a totally new thing to spec

Unfamiliar is OK. I don't think that non-technical people will use it. For now, it's better to implement it in a way that it will not break anything and still will provide expected features.

Totally new is OK too. It means that it will not interfere with something existing and old. `mailto:` also was a new thing back in the days, I guess. They could've just created `https://gmail.com/#mailTo:...` or something like that, and expect every online email service to support it. And now it's supported very good, you can even choose which website to use for `mailto` and it integrates with `gmail` really nice. I remember how it used to open default windows app, it was odd.

**Comment by bokand** [comment]
#15 has an interesting proposal to address this so will track this issue from there.
