### ISSUE TITLE
What if you want to select the nth occurrence of text?

### ISSUE THREAD

**Issue by isiahmeadows** [bokand/ScrollToTextFragment#9]
If the page has more than one instance of text, it might be useful to select a particular occurrence of text. For example, you might have a page structure like this (pretend each of these are headers, where indentation signifies hierarchy):

- Product 1
	- Description
	- Parts included
	- Reviews
- Product 2
	- Description
	- Parts included
	- Reviews
- Product 3
	- Description
	- Parts included
	- Reviews

Now suppose you want to link the parts included within Product 2 to someone. How would you do that, rather than accidentally linking "Parts included" for Product 1?

**Comment by dwhly** [comment]
This issue and possible solutions are being discussed here: https://github.com/bokand/ScrollToTextFragment/issues/4

**Comment by bokand** [comment]
Agreed, I think the proposals in #4 are promising so closing in favour of that.
